"""
Seeds the database with the same demo catalog the Next.js frontend currently
uses from lib/products.ts. Run with:

    python -m app.seed
"""

from .database import ensure_indexes, get_db

PRODUCTS = [
    {
        "id": "001",
        "slug": "classic-black-tshirt",
        "name": "Classic Black T-Shirt",
        "category": "Men",
        "subcategory": "T-Shirts",
        "price": 1690,
        "colors": [
            {"name": "Black", "hex": "#1A1A1A"},
            {"name": "White", "hex": "#F2F2F0"},
            {"name": "Charcoal", "hex": "#4A4A47"},
        ],
        "sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "unavailable_sizes": [],
        "description": "A heavyweight cotton tee cut for daily wear, with a clean crew neck that holds its shape wash after wash.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "created_at": "2026-08-20",
        "popularity": 92,
        "rating": 4.8,
        "review_count": 312,
    },
    {
        "id": "002",
        "slug": "oversized-white-tshirt-men",
        "name": "Oversized White T-Shirt",
        "category": "Men",
        "subcategory": "T-Shirts",
        "price": 1890,
        "compare_at_price": 2400,
        "colors": [
            {"name": "White", "hex": "#F5F3EE"},
            {"name": "Sand", "hex": "#D9CDB6"},
        ],
        "sizes": ["S", "M", "L", "XL"],
        "unavailable_sizes": [],
        "description": "A drop-shoulder tee in brushed cotton, roomy through the body for an easy, oversized fit.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "created_at": "2026-08-25",
        "popularity": 58,
        "rating": 4.4,
        "review_count": 96,
    },
    {
        "id": "003",
        "slug": "premium-oxford-shirt",
        "name": "Premium Oxford Shirt",
        "category": "Men",
        "subcategory": "Shirts",
        "price": 3490,
        "colors": [
            {"name": "White", "hex": "#F5F3EE"},
            {"name": "Light Blue", "hex": "#AFC2D6"},
            {"name": "Navy", "hex": "#26344A"},
        ],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "unavailable_sizes": [],
        "description": "A structured Oxford weave with a button-down collar — sharp enough for the office, easy enough for the weekend.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "created_at": "2026-06-10",
        "popularity": 81,
        "rating": 4.7,
        "review_count": 188,
    },
    {
        "id": "004",
        "slug": "slim-fit-blue-jeans",
        "name": "Slim Fit Blue Jeans",
        "category": "Men",
        "subcategory": "Jeans",
        "price": 4290,
        "compare_at_price": 5200,
        "colors": [
            {"name": "Indigo", "hex": "#3B4B6B"},
            {"name": "Black", "hex": "#1E1E1E"},
        ],
        "sizes": ["30", "32", "34", "36", "38"],
        "unavailable_sizes": ["38"],
        "description": "Mid-rise stretch denim tapered through the leg for a slim, tailored line without restricting movement.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "created_at": "2026-05-15",
        "popularity": 88,
        "rating": 4.6,
        "review_count": 245,
    },
    {
        "id": "005",
        "slug": "relaxed-fit-trousers",
        "name": "Relaxed Fit Trousers",
        "category": "Men",
        "subcategory": "Trousers",
        "price": 3190,
        "colors": [
            {"name": "Khaki", "hex": "#B9A67D"},
            {"name": "Charcoal", "hex": "#4A4A47"},
            {"name": "Olive", "hex": "#5B5A3F"},
        ],
        "sizes": ["30", "32", "34", "36"],
        "unavailable_sizes": [],
        "description": "A tapered relaxed fit in brushed twill, with a comfortable elastic waistband under the belt loops.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "created_at": "2026-04-02",
        "popularity": 45,
        "rating": 4.2,
        "review_count": 58,
    },
    {
        "id": "006",
        "slug": "classic-hoodie-men",
        "name": "Classic Hoodie",
        "category": "Men",
        "subcategory": "Hoodies",
        "price": 3990,
        "colors": [
            {"name": "Charcoal", "hex": "#3A3A38"},
            {"name": "Black", "hex": "#1A1A1A"},
            {"name": "Stone", "hex": "#C9C2B4"},
        ],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "unavailable_sizes": [],
        "description": "A midweight fleece hoodie with a lined hood and kangaroo pocket, built for everyday layering.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "created_at": "2026-08-15",
        "popularity": 63,
        "rating": 4.5,
        "review_count": 141,
    },
    {
        "id": "007",
        "slug": "denim-jacket-men",
        "name": "Denim Jacket",
        "category": "Men",
        "subcategory": "Jackets",
        "price": 6490,
        "colors": [{"name": "Indigo", "hex": "#3B4B6B"}],
        "sizes": ["S", "M", "L", "XL"],
        "unavailable_sizes": [],
        "description": "A classic trucker silhouette in rigid denim that softens and fades with wear.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "created_at": "2026-03-10",
        "popularity": 76,
        "rating": 4.6,
        "review_count": 173,
    },
    {
        "id": "008",
        "slug": "oversized-tshirt-women",
        "name": "Oversized T-Shirt",
        "category": "Women",
        "subcategory": "T-Shirts",
        "price": 1790,
        "colors": [
            {"name": "White", "hex": "#F5F3EE"},
            {"name": "Black", "hex": "#1A1A1A"},
            {"name": "Blush", "hex": "#DCC0B8"},
        ],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "unavailable_sizes": [],
        "description": "A soft, drapey oversized tee in combed cotton — pairs equally well with denim or a slip skirt.",
        "is_new_arrival": True,
        "is_best_seller": False,
        "created_at": "2026-08-28",
        "popularity": 55,
        "rating": 4.3,
        "review_count": 87,
    },
    {
        "id": "009",
        "slug": "casual-dress",
        "name": "Casual Dress",
        "category": "Women",
        "subcategory": "Dresses",
        "price": 4590,
        "compare_at_price": 5990,
        "colors": [
            {"name": "Terracotta", "hex": "#A1543A"},
            {"name": "Navy", "hex": "#26344A"},
        ],
        "sizes": ["XS", "S", "M", "L"],
        "unavailable_sizes": [],
        "description": "A midi-length wrap dress in a fluid crepe, cut to move with you from desk to dinner.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "created_at": "2026-08-05",
        "popularity": 90,
        "rating": 4.9,
        "review_count": 264,
    },
    {
        "id": "010",
        "slug": "wide-leg-jeans",
        "name": "Wide Leg Jeans",
        "category": "Women",
        "subcategory": "Jeans",
        "price": 4390,
        "colors": [
            {"name": "Indigo", "hex": "#3B4B6B"},
            {"name": "Black", "hex": "#1E1E1E"},
        ],
        "sizes": ["26", "28", "30", "32", "34"],
        "unavailable_sizes": [],
        "description": "High-rise wide-leg denim with a clean, uncuffed hem — the fit that anchors a whole outfit.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "created_at": "2026-02-20",
        "popularity": 40,
        "rating": 4.1,
        "review_count": 42,
    },
    {
        "id": "011",
        "slug": "basic-top",
        "name": "Basic Top",
        "category": "Women",
        "subcategory": "Tops",
        "price": 1590,
        "colors": [
            {"name": "White", "hex": "#F5F3EE"},
            {"name": "Black", "hex": "#1A1A1A"},
            {"name": "Sage", "hex": "#9AA88C"},
        ],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "unavailable_sizes": [],
        "description": "A fitted ribbed top that layers cleanly under blazers or stands on its own with high-waist denim.",
        "is_new_arrival": False,
        "is_best_seller": False,
        "created_at": "2026-01-15",
        "popularity": 35,
        "rating": 4.0,
        "review_count": 33,
    },
    {
        "id": "012",
        "slug": "premium-hoodie-women",
        "name": "Premium Hoodie",
        "category": "Women",
        "subcategory": "Hoodies",
        "price": 3890,
        "compare_at_price": 4600,
        "colors": [
            {"name": "Stone", "hex": "#C9C2B4"},
            {"name": "Black", "hex": "#1A1A1A"},
        ],
        "sizes": ["XS", "S", "M", "L"],
        "unavailable_sizes": [],
        "description": "A cropped, brushed-fleece hoodie with a relaxed drop shoulder and ribbed hem.",
        "is_new_arrival": True,
        "is_best_seller": True,
        "created_at": "2026-08-10",
        "popularity": 84,
        "rating": 4.7,
        "review_count": 201,
    },
    {
        "id": "013",
        "slug": "denim-jacket-women",
        "name": "Denim Jacket",
        "category": "Women",
        "subcategory": "Jackets",
        "price": 5990,
        "colors": [
            {"name": "Light Wash", "hex": "#93A9C2"},
            {"name": "Indigo", "hex": "#3B4B6B"},
        ],
        "sizes": ["XS", "S", "M", "L"],
        "unavailable_sizes": [],
        "description": "A cropped denim jacket with a boxier shoulder, made to be worn open over everything.",
        "is_new_arrival": False,
        "is_best_seller": True,
        "created_at": "2026-03-25",
        "popularity": 70,
        "rating": 4.5,
        "review_count": 122,
    },
]


def seed():
    db = get_db()
    ensure_indexes(db)

    inserted, skipped = 0, 0
    for product in PRODUCTS:
        if db.products.find_one({"slug": product["slug"]}):
            skipped += 1
            continue
        db.products.insert_one(dict(product))
        inserted += 1

    print(f"Seed complete — inserted {inserted}, skipped {skipped} (already existed).")


if __name__ == "__main__":
    seed()
